version: "3"
services:
  app:
    build:
      args:
        user: succotash
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: leonardovee/succotash
    container_name: succotash-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - succotash
  db:
    image: mysql:latest
    container_name: succotash-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - succotash
  nginx:
    image: nginx:1.17-alpine
    container_name: succotash-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - succotash
networks:
  succotash:
    driver: bridge
