version: "3.5"

services:
  effective-succotash-api:
    container_name: effective-succotash-api
    build: .
    image: leonardovee/effective-succotash
    ports:
      - "8080:8080"
    networks:
      - effective-succotash
    restart: unless-stopped

  effective-succotash-postgres:
    container_name: effective-succotash-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - effective-succotash
    restart: unless-stopped

  effective-succotash-pgadmin:
    container_name: effective-succotash-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - effective-succotash
    restart: unless-stopped

networks:
  effective-succotash:
    driver: bridge
volumes:
  postgres:
  pgadmin: